version: "3.4"

services:

  app:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    image: clearboard
    user: ${DOCKER_USER:-1000}
    env_file:
      - env.d/development
    ports:
      - "8070:8000"
    volumes:
      - ./src/backend:/app

  lambda:
    build:
      context: ./src/terraform
    image: clearboard-enhance
    env_file:
      - env.d/lambda
    command: ["lambda-enhance.app.handler"]
    ports:
      - 9000:8080
    volumes:
      - "./src/terraform/lambda-enhance:/var/task/lambda-enhance"

  terraform-state:
    image: hashicorp/terraform:1.1.6
    env_file:
      - env.d/terraform
    user: ${DOCKER_USER:-1000}
    working_dir: /app
    volumes:
      - ./src/terraform/create_state_bucket:/app

  terraform:
    image: hashicorp/terraform:1.1.6
    env_file:
      - env.d/terraform
    user: ${DOCKER_USER:-1000}
    working_dir: /app
    volumes:
      - ./src/terraform:/app
